from django.shortcuts import render, redirect

context = {'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean finibus fermentum lacus volutpat lacinia. Aliquam aliquet, lectus a tempor dignissim, lectus erat condimentum ligula, in malesuada risus orci eget nibh. Curabitur rutrum molestie est in vulputate. Suspendisse potenti. Sed dolor enim, fringilla in libero sed, venenatis semper tortor. Pellentesque imperdiet velit enim, ac efficitur tellus vestibulum ut. Ut sit amet velit molestie libero ultrices dapibus. Integer lorem dui, fringilla nec facilisis id, lacinia faucibus ante. Pellentesque in augue quis nisi interdum ultricies ac eget arcu. Curabitur scelerisque dignissim iaculis. Morbi sagittis congue euismod. Nam rhoncus, neque in vulputate bibendum, dui eros imperdiet erat, eu scelerisque metus urna sed turpis. In velit ante, tristique non diam rutrum, tempor varius urna. In hac habitasse platea dictumst. Aenean ultrices sollicitudin lacinia. Aliquam sem elit, molestie a tellus eget, ultrices semper urna. Nulla quis pellentesque urna. Duis neque justo, ornare nec nulla maximus, pulvinar vehicula urna. Aliquam varius nisi ut eros bibendum interdum. Nunc in diam tempus lacus auctor condimentum vel rhoncus diam. Quisque venenatis gravida ipsum, quis dignissim neque tincidunt in. Sed dictum sed libero id consequat. Duis ornare nisi libero, vel lacinia odio accumsan et. Duis fringilla pellentesque neque, a luctus magna condimentum et. Cras interdum non dui eu consequat. Aenean imperdiet arcu felis, a cursus nisl malesuada vitae. Mauris in congue neque, sed sollicitudin leo. Nulla mollis risus tortor, vel vehicula lectus suscipit quis. Nam dictum nec quam ac fermentum. Vestibulum sed nunc tortor. Proin pharetra, neque eget porta aliquam, nulla ex iaculis diam, sed porttitor massa lorem vel nisi. Ut sed dictum risus, sit amet imperdiet leo. Aliquam pellentesque mauris ut tortor feugiat viverra. Menas nec mauris ac sem sagittis sodales. Mauris nec ligula nec est elementum tristique sit amet in nisl. Donec tempor a metus et mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi faucibus tortor vel sem tincidunt auctor. Pellentesque suscipit et dui et auctor. Ut sit amet suscipit dolor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi malesuada ligula et nisl volutpat, vel ornare tortor dapibus. Aenean tempor arcu neque, rutrum porttitor sem pellentesque sit amet. Pellentesque sit amet tellus quis tellus varius sodales eu sed risus. Maecenas auctor ipsum nec bibendum vestibulum. Proin venenatis ornare tortor eu porttitor. Suspendisse bibendum mi sed dictum egestas. Maecenas a purus vestibulum purus aliquam volutpat sed sed erat. Duis vitae tristique justo. Etiam at pharetra velit, accumsan facilisis metus.'}

def about(request):
    if 'back' in request.GET:
        return redirect('upload_pic_homepage')
    else:
        return render(request, 'about/about.html', context)
